export const ROUTES = {
  HOME: '/',
  CRIAR: '/criar',
  CRIAR_EDITOR: '/criar/editor',
  CRIAR_QRCODE: '/criar/qrcode',
  CRIAR_PREVIEW: '/criar/preview',
  CRIAR_PLANO: '/criar/plano',
  CRIAR_PAGAMENTO: '/criar/pagamento',
  CRIAR_SUCESSO: '/criar/sucesso',
  PAINEL: '/painel',
  PAINEL_VERIFICAR: '/painel/verificar',
  PAINEL_SITES: '/painel/sites',
  SITE_PUBLICO: '/site/:slug',
  POLITICA: '/politica-privacidade',
  TERMOS: '/termos-de-uso',
} as const
